export const SHOW_CAPACITY = 'SHOW_CAPACITY'
export const SHOW_LOADING = 'SHOW_LOADING'
export const SHOW_CHRONOLOGY = 'SHOW_CHRONOLOGY'
export const SHOW_START = 'SHOW_START'
export const SHOW_SUCCESS = 'SHOW_SUCCESS'
export const SHOW_FAIL = 'SHOW_FAIL'
export const SEND_DATE = 'SEND_DATE'